M48
; DRILL file {KiCad 8.0.1} date 2024-04-03T17:05:06+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-03T17:05:06+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0689
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0709
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.0886
%
G90
G05
T1
X4.3394Y-3.8262
X4.3394Y-4.0171
T2
X4.7047Y-1.6339
X6.2795Y-1.6339
T3
X4.2201Y-3.8144
X4.2201Y-4.0289
T4
X5.0098Y-1.5157
X6.0138Y-1.5157
M30
